name: ml-general

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter
  - nb_conda_kernels
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - pytorch=1.11=py3.10_cuda11.3_cudnn8_0
  - cudatoolkit=11.3
  - optuna
  - matplotlib
  - seaborn